### ISSUE TITLE
Guide for using with Windows

### ISSUE THREAD

**Issue by alex1651** [Migz93/lidarr-download-automation#17] opened 2019-09-26 20:19 UTC
Would it be possible to get a guide for using this script with Windows? I am familiar with SMLoadr and have it set up and downloading files properly. I have my config file placed in the same folder as SMLoadr except, i am not sure of what extension to use for the config file. 

Thanks in advance

**Comment by Migz93** [comment] 2019-09-26 20:59
The most recent version of this script only works with linux for windows (WSL), not natively in Windows. I assume the recent version is what you're talking about as this is what has a config file.
The config file doesn't need an extension, it is named literally "config".

There's no real guide needed, all there is to this is the config file and the script, all the config file options are explained so you fill as required and then run it. If theres something you think can be made a little clearer let me know and i can work on that.

**Comment by alex1651** [comment] 2019-09-27 16:18
Here is what I have done so far
Enable WSL in Windows 10 by running Powershell as admin and running: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Downloaded and installed Ubuntu 18.04 LTS from the Microsoft store
Created my Unix use with a password
Made sure Ubuntu is up to date and fully upgraded
Downloaded and installed Lidarr using: https://github.com/Lidarr/Lidarr/wiki/Installation#linux
Made sure I could access the Lidarr webgui
Downloaded SMLoadr

Things I’m struggling with:
Installing SMLoadr
Downloading and installing SMLoadr-Lidarr script
I would appreciate any help that you could provide in this. I can write up a guide for this, once I have mine all up and working properly.

**Comment by Migz93** [comment] 2019-09-27 17:28
Haven't tried running Lidarr under WSL, the testing was for Lidarr on windows and the script under WSL.
It'll probably still work though, where would you be wanting your files to end up? Because that would change whether to set WSL mode in the config or not.

As for your questions:
- **Installing SMLoadr**
It's not something you installed, it's just a file that runs. Once you've downloaded it you need to mark it as executable so do `sudo chmod +x SMLoadr-linux-x64`
- **Downloading and installing SMLoadr-Lidarr script**
Again, it's not something you install, it's just a script file that you run. To download it, ideally
`sudo apt update && sudo apt install git` This installs git, may already be installed by default with WSL.
`cd /opt/ && git clone https://github.com/Migz93/lidarr_smloadr_script.git` This downloads the repo to /opt/lidarr_smloadr_script.
`sudo chmod +x /opt/lidarr_smloadr_script/lidarr-smloadr.sh` This marks the script as executable so you can run it.

- **Bonus Tips**
Then you'd copy the config file.
`cp /opt/lidarr_smloadr_script/config.sample /opt/lidarr_smloadr_script/config`
Edit the config file and fill out your settings.
`nano /opt/lidarr_smloadr_script/config` 
Then finally you'd run the lidarr script once configured
`cd /opt/smloadr && /bin/bash lidarr-smloadr.sh`

Note: You should ideally move the SMLoadr executable file into the same directory as the script.

**Comment by alex1651** [comment] 2019-09-27 21:20
Thanks for the reply, sorry for my noob questions, i am fairly new to linux cmd.  I have that solved now and i have my config edited and saved. I have everything saved in /opt/SMLoadr/lidarr_smloadr_script when i run ./lidarr-smloadr.sh i get the following error:
![smloadr_lidarr run error](https://user-images.githubusercontent.com/15963866/65802665-388e2e80-e131-11e9-9f3e-ad289e9fbb80.png)
Here is what my config file looks like
![smloadr_lidarr config](https://user-images.githubusercontent.com/15963866/65802920-e00b6100-e131-11e9-8c4b-59801faa4d2c.png)

Thanks as always

**Comment by Migz93** [comment] 2019-09-27 21:22
You've spelt the `scriptDir` path wrong in your config. You've typed "smloar` instead of `smloadr`.
Correct that and see if you have any luck

**Comment by alex1651** [comment] 2019-09-27 22:06
I fixed that, not having autocomplete makes for mistakes. The script is working now. Should i have to run it as sudo in wsl? or maybe do i have something set up wrong? I will continue to play with this and get it tweaked as it currently downloads the same album over again, but says song already exists. Do you have a place that i can send a donation or buy you a coffee or a beer?

**Comment by Migz93** [comment] 2019-09-29 10:44
Shouldn't have to run it as sudo, i don't think i did when in WSL.
As for downloading the same album over and over, that's a bit strange, do you have other albums marked as wanted?
No need for a donation or buy me anything, I'm always happy to help

**Comment by alex1651** [comment] 2019-09-29 14:46
Alright, yea I do have other albums marked as wanted. Upon further checking it appears to be doing fuzzy searches on albums that it didn’t get the first time. I am still playing with it and need to look over the logs to see what is happening.

**Comment by Migz93** [comment] 2019-10-20 15:37
Hi Alex, did you get anywhere with a guide for windows?

**Comment by alex1651** [comment] 2019-10-22 03:51
I'm still working on getting it written up. I'm still having a few issues getting things to download correctly. I will write up what I have and get it to you.

**Comment by pekempy** [comment] 2019-11-14 13:06
I'm having issues getting it going on Windows too. Currently getting an error when running the script
`Lidarr communication error, check LidarrUrl in config or LidarrApiKey`

I've checked the URL, tried using http://localhost:8686, http://127.0.0.1:8686, http://192.168.1.x:8686, and my external URL which I obviously won't post here.    
I've also generated a new API key and put that in, restarted Lidarr, and still no luck


I wrote up a lil guide while I was doing it 

## Windows Guide
**    
Download [SMLoadr-linux-x64](https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr/releases)
Unzip and place in folder 
Open Linux Shell in folder (shift+right click)
`sudo chmod +x SMLoadr-linux-x64`
`./SMLoadr-linux-x64`
Set up SMLoadr ([ARL cookie](https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr/wiki/How-to-login-via-cookie), quality, download mode ALL etc)
`CTRL + C` to quit
Download [lidarr-download-automation.bash](https://github.com/Migz93/lidarr-download-automation)
Set up [config file]([https://github.com/Migz93/lidarr-download-automation/blob/develop/config.sample](https://github.com/Migz93/lidarr-download-automation/blob/develop/config.sample)) and remove ".sample" from the extension.
- mode=wanted
- wantedalbumsamount=10
- quality to match SMLoadr
-  lidarr URL/API
-  directories    

Run `bash ./lidarr-download-automation.bash` in Linux Shell

**Comment by RandomNinjaAtk** [comment] 2019-11-20 11:59
Did you make sure all the dependencies are installed? curl, jq, etc...

**Comment by pekempy** [comment] 2019-11-21 15:57
> @pekempy Thanks for the mini guide, i'll see if i can add a few more specifics like exact folders to put it in and then i'll add it to the wiki.
> As for your error can you try running the following in linux shell and see if it returns anything
> 
> ```
> lidarrApiKey="APIKEY"
> lidarrUrl="LidarrURL+Port"
> 
> curl -s --header "X-Api-Key:"${lidarrApiKey} --request GET "$lidarrUrl/api/v1/wanted/missing/?page=1&pagesize=10&includeArtist=true&monitored=true&sortDir=desc&sortKey=releaseDate"
> ```

Yeah, it does return a crap load of JSON, likely all that should be downloaded. 
curl, jq, flac, mp3val and ffmpeg are all installed 100%.

**Comment by pekempy** [comment] 2019-11-23 14:52
Quick video - test.bash has the curl command with lidarr api key and lidarr url.
Have tried using sudo also, no success.
https://screencast-o-matic.com/watch/cqX02KUyuI
@Migz93 @RandomNinjaAtk

**Comment by pekempy** [comment] 2019-11-26 12:02
Update: works in artist mode, but I am gonna try and get it going in wanted mode too... looks like error is occurring line 336

**Comment by Migz93** [comment] 2019-11-26 12:06
Thanks for keeping us updated. I'm trying to reproduce the problem my side whenever i have spare time but struggling to get it to fail.

**Comment by pekempy** [comment] 2019-11-26 12:06
I can give you TeamViewer access if you'd like to see? Are you on discord?

**Comment by Migz93** [comment] 2019-11-26 12:31
Yeah i'd literally just found the same, set it up fresh in WSL and it worked fine.
Copied your config over and it started failing, found that the WantedModeType line was missing completely. Also, your WSL mode is set to false, you'll need to set that to true otherwise Lidarr may not be able to import your downloads.

Glad you've got it working though!

**Comment by pekempy** [comment] 2019-11-26 12:33
Yeah I've got it back on True now. Turns out I just needed to debug for a bit :)
Not sure if the `$LidarrUrl` should be `${LidarrUrl}` on [this line](https://github.com/Migz93/lidarr-download-automation/blob/develop/lidarr-download-automation.bash#L43)?

**Comment by Migz93** [comment] 2019-11-26 12:47
Either one works fine don't worry. I can't remember the exact reason why $LidarrUrl is used there, i think it's how i originally referenced variables, since then we've swapped to using ${LidarrUrl} as the variable format. It won't break anything, works as expected. We'll eventually tidy up the code so it's more uniform.

I've copied your guide over [here](https://github.com/Migz93/lidarr-download-automation/wiki/Running-On-Windows-(WSL)) so I'm going to close this issue.

If you need any help with anything us feel free to open an issue for it :).

**Closed by Migz93** 2019-11-26 12:47 UTC
